name: Build Image & deploy to Amazon ECS

on:
  push:
    branches:
      - main

env:
  AWS_REGION: eu-south-2
  ECR_REPOSITORY: test-ecr

jobs:
  CI:
    name: Build and deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_USR_ECR }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_USR_ECR }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build, tag, and push docker image to Amazon ECR
      env:
        REPOSITORY_URI: ${{ secrets.REPOSITORY_URL }}
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build -t $REPOSITORY_URI:$IMAGE_TAG .
        docker push $REPOSITORY_URI:$IMAGE_TAG